expname: nsff
basedir: ./logs
trainer: nsff

dataset:
  name: dynamic
  root_dir: ./data/kid
  resolution: 0.5

# model
model:
  depth: 8
  width: 256
  xyz_embed_dim: 10  # for positional encoding
  dir_embed_dim: 4  # for positional encoding
  tra_embed_dim: 16  # for transient embedding
  skips: [4]  # add skip connection in the Dth layer

# Hyperparameters
iters: 150000  # total training iterations
lr: 5e-4
momentum: 0.9
weight_decay: 0.0
scheduler:
  decay_step: [120000]
  decay_gamma: 0.1

batch_size: 1024  # number of uniformly sampled rays per batch
num_extra_samples: 512  # extra rays hard-mined from the dynamic region
decay_iteration: 30  # losses/hard-mining decay every decay_iteration * 1000
chunk: 8192  # number of rays processed for inference
N_samples: 128
perturb: 1.0
noise_std: 1.0
gpu: 0
